# Operaciones con matrices en python con numpy

En este cuaderno o notebook podrás ver ejemplos de las siguientes operaciones con matrices en numpy:

- Suma y Resta
- Multiplicación de matrices
- Multiplicación de matrices entrada por entrada
- Transpuesta de una matriz
- Producto punto entre vectores
- Multiplicar vector por matriz fila por fila
- Multiplicar vector por matriz columna por columna

Si quieres ver una explicación en formato video puedes ver [este video](https://youtu.be/7JSHBwi776A) (disponible a partir del **2024-06-08**)

*Nota: Si no sabes qué es google colab, ve [este video](https://youtu.be/ihzCr92RbRo).*

## Importar librerías

In [ ]:
import numpy as np

## Definir matrices de prueba

In [ ]:
A = np.array([[1, 3],
              [2, 4]])

B = np.array([[1, 0],
              [0,-1]])

## Suma y Resta

In [ ]:
print(A, B, "", sep="\n")
print(A + B)

[[1 3]
 [2 4]]
[[ 1  0]
 [ 0 -1]]

[[2 3]
 [2 3]]


In [ ]:
print(A, B, "", sep="\n")
print(A - B)

[[1 3]
 [2 4]]
[[ 1  0]
 [ 0 -1]]

[[0 3]
 [2 5]]


## Multiplicación de matrices y Multiplicación entrada por entrada

In [ ]:
print(A, B, "", sep="\n")
print(A @ B)

[[1 3]
 [2 4]]
[[ 1  0]
 [ 0 -1]]

[[ 1 -3]
 [ 2 -4]]


In [ ]:
print(A, B, "", sep="\n")
print(A * B)

[[1 3]
 [2 4]]
[[ 1  0]
 [ 0 -1]]

[[ 1  0]
 [ 0 -4]]


## Transpuesta de una matriz

In [ ]:
print(A, "", sep="\n")
print(A.T)

[[1 3]
 [2 4]]

[[1 2]
 [3 4]]


## Definir vectores de prueba

In [ ]:
u = np.array([1, 2])
v = np.array([1, 0])

## Producto punto

In [ ]:
print(u, v, "", sep="\n")
print(np.dot(u, v))

[1 2]
[1 0]

1


In [ ]:
print(u, v, "", sep="\n")
print(u @ v)

[1 2]
[1 0]

1


## Multiplicar vector por matriz fila por fila

In [ ]:
print(u, A, "", sep="\n")
print(u * A)

[1 2]
[[1 3]
 [2 4]]

[[1 6]
 [2 8]]


## Multiplicar vector por matriz columna por columna

In [ ]:
print(u, A, "", sep="\n")
print((u * A.T).T)

[1 2]
[[1 3]
 [2 4]]

[[1 3]
 [4 8]]
