# Abrir y Guardar archivos CSV en python

En este cuaderno o notebook podrás ver ejemplos de cómo:

- Abrir un archivo CSV con pandas
- Abrir un archivo CSV sin pandas
- Guardar un archivo CSV con pandas
- Guardar un archivo CSV sin pandas

Si quieres ver una explicación en formato video puedes ver [este video](https://youtu.be/iXv4bBG3qKc) (disponible a partir del **2024-06-16**)

*Nota: Si no sabes qué es google colab, ve [este video](https://youtu.be/ihzCr92RbRo).*

## Importar librerías

In [ ]:
import pandas as pd
import numpy as np

## Crear archivo de prueba

In [ ]:
with open("archivo.csv", "w") as f:
  f.write("col1,col2,col3\n")
  for i in range(10):
    datos = np.random.randint(0,10,3)
    f.write(f"{datos[0]},{datos[1]},{datos[2]}\n")

## Abrir CSV

In [ ]:
# Usando pandas
datos = pd.read_csv("archivo.csv")
datos

col1  col2  col3
0     0     8     3
1     3     2     2
2     6     3     6
3     1     6     7
4     1     2     0
5     1     2     0
6     8     1     3
7     7     9     1
8     3     9     5
9     4     1     6

In [ ]:
# Sin librerías
with open("archivo.csv", "r") as archivo:
  print(archivo.readline())
  print(archivo.readlines())


col1,col2,col3

['0,8,3\n', '3,2,2\n', '6,3,6\n', '1,6,7\n', '1,2,0\n', '1,2,0\n', '8,1,3\n', '7,9,1\n', '3,9,5\n', '4,1,6\n']


## Guardar CSV

In [ ]:
# Generar datos
columnas = ["col1", "col2", "col3"]
valores = np.random.randint(0, 10, (10,3))
print(valores)

[[8 3 2]
 [3 6 2]
 [7 1 9]
 [2 5 9]
 [8 5 0]
 [7 9 4]
 [1 6 6]
 [6 3 8]
 [5 3 1]
 [6 7 7]]


In [ ]:
# Con pandas
datos = pd.DataFrame(valores, columns=columnas)
display(datos)
datos.to_csv("archivo_pandas.csv", index=False)

col1  col2  col3
0     8     3     2
1     3     6     2
2     7     1     9
3     2     5     9
4     8     5     0
5     7     9     4
6     1     6     6
7     6     3     8
8     5     3     1
9     6     7     7

In [ ]:
# Sin librerías
with open("archivo_sin_lib.csv", "w") as archivo:
  # Agregar nombres de columnas
  archivo.write(",".join(columnas)+"\n")


  # Guardar valores en archivo
  for i in range(valores.shape[0]):
    # Crear string de valores por fila
    fila_de_valores = f"{valores[i,0]},{valores[i,1]},{valores[i,2]}\n"
    # Guardar string de valores por fila
    archivo.write(fila_de_valores)
